image: null

variables:
  SG_CI_IMAGE_NAME: "ci:1.3"
  SKIP_NATIVE: "false"
  SKIP_E2E: "false"
  SKIP_DEPLOY: "false"
  E2E_SHELL: sh
  E2E_ENV: kind
  E2E_PARALLELISM: 32
  E2E_JOBS: 3
  E2E_EXCLUSIVE_JOBS: 3
  K8S_VERSION: 1.16.15
  K8S_FROM_DIND: "true"
  K8S_REUSE: "true"
  LATEST: "false"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

stages:
  - pre build
  - build 1
  - build 2
  - build 3
  - check release
  - native build
  - image build
  - test
  - deploy

include:
  - local: .gitlab-ci/pre-build.yml
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/native-build.yml
  - local: .gitlab-ci/image-build.yml
  - local: .gitlab-ci/test.yml
  - local: .gitlab-ci/check-release.yml
  - local: .gitlab-ci/deploy.yml
