
enforce release:
  image: docker.io/ongres/ubi-graalvm-maven:21.0.0.2-java11
  stage: check release
  tags:
    - stackgres-runner
  script:
    - MAVEN_CLI_OPTS="$MAVEN_CLI_OPTS -Dmaven.test.skip=true -Dquarkus.build.skip=true"
    - 'mvn $MAVEN_CLI_OPTS enforcer:enforce@enforce-no-snapshots'
  only:
    variables:
      - $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
