apiVersion: v2
name: stackgres-cluster
version: "1.0.0-beta3-SNAPSHOT"
kubeVersion: "1.11.0-0 - 1.21.x-0"
description: StackGres Cluster
keyworkds:
  - stackgres
  - postgresql
  - postgres
  - cluster
  - stack
  - opinionated
home: https://stackgres.io
sources:
  - https://gitlab.com/ongresinc/stackgres
maintainers: 
  - name: OnGres Inc.
    email: info@ongres.com
    url: https://ongres.com
engine: gotpl
icon: https://assets.gitlab-static.net/uploads/-/system/project/avatar/12584701/logo-stackgres.png?width=64
appVersion: "1.0.0-beta3-SNAPSHOT"
deprecated: false
